YEAR = "year"
COURSE = "course"
CREDIT = "credit"
SUBJECT = "subject"
ROTATIONS = "Rotations"
COURSE_NAME = "course_name"
DESCRIPTIONS = "descriptions"
PREREQUISITE = "prerequisite"
COURSE_NUMBER = "course_number"
ROTATION_TERM = "rotation_term"
ROTATION_YEAR = "rotation_year"
COURSE_DESCRIPTION = "course_description"

# Constant values corresponding to XML/Json file paths
MERGED_JSON_FILE = "data.json"
COURSE_XML_FILE = "courses.xml"
COURSE_JSON_FILE = "courses.json"
ROTATION_XML_FILE = "rotation.xml"
ROTATION_JSON_FILE = "rotation.json"